# Python Standards Configuration
version = "0.2.0"
formatter = "black"
linter = "flake8"
type_checker = "mypy"
test_framework = "pytest"
line_length = 88
python_version = "3.13"

[black]
line_length = 88
target_version = ["py313"]
include = '\.pyi?$'

[isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["{{ project_name }}"]

[mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[pytest]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov={{ project_name }} --cov-report=term-missing --cov-report=html"

[flake8]
max_line_length = 88
extend_ignore = ["E203", "W503"]
exclude = [
  ".git",
  "__pycache__",
  "build",
  "dist",
  ".venv",
  "venv",
  ".tox",
  ".pytest_cache",
]
