# Sympulse Coding Standards Configuration
version = "0.2.0"
languages = ["python", "typescript"]
strict_mode = false
auto_fix = true

[global]
# Global settings that apply to all languages
project_structure = "modular"
documentation_required = true
testing_required = true
code_review_required = true

[git]
# Git workflow standards
branch_naming = "feature/description or fix/description"
commit_message_format = "type(scope): description"
protected_branches = ["master", "develop"]
required_status_checks = ["lint", "test", "build"]

[ci_cd]
# CI/CD standards
platforms = ["github_actions", "gitlab_ci"]
required_stages = ["lint", "test", "build", "deploy"]
code_quality_gates = true
security_scanning = true

[documentation]
# Documentation standards
readme_required = true
contributing_guide_required = true
api_documentation_required = false
changelog_required = true
